.devops/azure-templates/e2e-tests.yaml
.devops/code-review-pipelines.yml

depend on: https://github.com/pagopa/pagopa-wallet-tests/pull/2
👉🏻 Added CR pipeline and azure template pipeline for execute E2E tests
Added new
The change was made to add CR pipeline

feat: CHK 2030 added CR pipeline

---

.devops/azure-templates/e2e-tests.yaml
.devops/code-review-pipelines.yml
README.md

depend on: https://github.com/pagopa/pagopa-wallet-tests/pull/3
👉🏻 Modified readme with project description

feat: CHK-2032 added project readme

---

e2e-tests/src/PM/wallet.pm.onboarding.integration.test.ts

fix: modified timeout for test

---

api-tests/dev.envs.json
api-tests/uat.envs.json
api-tests/wallet_payment_api.tests.json

Add wallet payment api test collection
Add postman collection, dev and uat env json files
This PR is required for deploy dev and uat pipelines

[CHK-2067] Add wallet payment api test collection

---

.devops/azure-templates/e2e-tests.yaml
e2e-tests/package.json

- dev executes npg tests
- uat executes pm tests

[CHK-2110] Env conditional tests

---

api-tests/wallet_payment_api.cards.tests.json
api-tests/wallet_payment_api.paypal.tests.json

Fix integration tests assertions
Fix integration tests assertions
Integration test run

fix: integration tests assertions

---

api-tests/wallet_payment_api.cards.tests.json
api-tests/wallet_payment_api.paypal.tests.json

Differentiate apm and credit cards onboarding api tests descriptions
Differentiate apm and credit cards onboarding api tests descriptions
Integration test run

fix: api test descriptions

---

api-tests/wallet_payment_api.paypal.tests.json

feat: modified token into GET user

---

.gitignore
api-tests/wallet_payment_api.cards.tests.json
api-tests/wallet_payment_api.paypal.tests.json

Add delete test for cards and paypal

[CHK-2596] update wallet api tests

---

api-tests/wallet_migration_api.tests.json

[CHK-2584] Migration - add test for update wallet with card details

---

api-tests/wallet_migration_api.tests.json

[CHK-2584] Migration - fix test for update wallet with card details

---

api-tests/wallet_migration_api.tests.json

[CHK-2588] Migration - Add tests for delete api

---

api-tests/wallet_migration_api.tests.json

[CHK-2584] Migration tests - rename originalContractId to contractIdentifier

---

api-tests/wallet_payment_api.paypal.tests.json

Fix wallet Paypal api tests pspId
Fix wallet Paypal api tests pspId

fix: api tests psp id

---

api-tests/wallet_payment_api.cards.tests.json
api-tests/wallet_payment_api.paypal.tests.json

Update integration tests for wallets api
- add PUT applications tests
- move GET wallets (by user id) and add delay to wait for npg notification url

[CHK-2723] feat(tests): update integration tests

---

api-tests/wallet_migration_api.tests.json

[CHK-2754] Add CSTAR API key for migration endpoints

---

api-tests/wallet_migration_api.tests.json

Update migration tests after adding check on duplicate paymentGatewayCardId
- generation of random paymentGatewayCardID

[CHK-2279] Migration Tests - Add random payment gateway card id

---

api-tests/dev.cards.envs.json
api-tests/dev.paypal.envs.json
api-tests/uat.cards.envs.json
api-tests/uat.paypal.envs.json
api-tests/wallet_payment_api.cards.tests.json
api-tests/wallet_payment_api.cardsPM.tests.json
api-tests/wallet_payment_api.paypal.tests.json
e2e-tests/dev.env
e2e-tests/jest-puppeteer.config.js
e2e-tests/src/NPG/helper.js
e2e-tests/src/NPG/wallet.npg.onboarding.integration.test.js
e2e-tests/src/NPG/wallet.npg.payment.integration.test.js
e2e-tests/src/PM/helper.js
e2e-tests/uat.env

Fix api tests to handle new authentication and new api for wallets
Fix also e2e test to handle new onboarding and payment flow with new apis
edit collections for new authentications and wallet routes

[CHK-2984] fix(api tests) fix api test for new routes and new authentication

---

e2e-tests/src/PM/helper.js
e2e-tests/src/PM/wallet.pm.onboarding.integration.test.ts

fix: PM test intercept outcome

---

soak-test/.env.example
soak-test/package.json
soak-test/src/common/config.ts
soak-test/src/soak-test-migration.ts
soak-test/src/soak-test-onboard-wallet-ingress.ts

Added soak tests to use directly on ingress for the CDC
We needed to make sure the previous solution mantained the level of operability and performance previously measured
Local test with postman and manual testing on UAT

Feat [CHK-3518]: Added soak tests for CDC (ingress)
